services:
  web:
    image: python:3.13-alpine
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - APP_NAME=$APP_NAME
